### ISSUE TITLE
easy_mace应用

### ISSUE THREAD

**Issue by charmowen** [conansherry/easy_mace#1]
已编译完成您的工程，请问如何将它应用于手机GPU图像object detection呢？您是否有这方面的demo可以学习一下呢？

**Comment by conansherry** [comment]
mace是很底层的一个库，所以想要进行上层的深度学习应用你得先准备好模型，mace支持tensorflow和caffe模型的转换，我这里整理的只是mace库的编译，关于模型的转换和库的调用方式可以参考小米mace的项目，里面有详细的文档 https://github.com/XiaoMi/mace

**Comment by chenzhaowen** [comment]
ok,thanks a lot!
