### ISSUE TITLE
half.hpp:275:8: error: missing space between '""' and suffix identifier

### ISSUE THREAD

**Issue by zhangkom** [conansherry/easy_mace#2]
In file included from ./../mace/core/types.h:23:0,
                 from ./../mace/core/allocator.h:27,
                 from ./core/allocator.cc:15:
./../external/half/include/half.hpp:275:8: error: missing space between '""' and suffix identifier
   half operator""_h(long double);
        ^
./../external/half/include/half.hpp:1086:24: error: missing space between '""' and suffix identifier
   friend half literal::operator""_h(long double);
                        ^
./../external/half/include/half.hpp:1199:15: error: missing space between '""' and suffix identifier
   inline half operator""_h(long double value) { return half(detail::binary, detail::float2half<half::round_style>(value)); }

**Comment by conansherry** [comment]
编译环境发一下

**Comment by zhangkom** [comment]
重新同步了就没这个问题了。
