### ISSUE TITLE
runtime_failure_mock.cc error: undefined reference to 'rand_r'你是怎么解决的？

### ISSUE THREAD

**Issue by akbarxie** [conansherry/easy_mace#4]
你好：
       我有看你的mace源代码，发现你改了一些：
         static unsigned int seed = time(NULL);
         std::srand(seed);
         float random_ratio = std::rand() / static_cast<float>(RAND_MAX);
不过我改了之后还是出现：
undefined reference to 'srand'，和undefined reference to 'rand'的问题。求教要怎么解决。

**Comment by conansherry** [comment]
https://en.cppreference.com/w/cpp/numeric/random/srand
看看是不是少包含了头文件

**Comment by akbarxie** [comment]
这个文件有添加#include <cstdlib>，我规避了这个问题
    long mySeed = seed&RAND_MAX;
    srand48(mySeed);
    float random_ratio = ((unsigned int)(lrand48()&RAND_MAX)) / static_cast<float>(RAND_MAX);
    //float random_ratio = std::rand_r(&seed) / static_cast<float>(RAND_MAX);

thanks！！
